spring.application.name=DentalCare-BackendApi

#database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dentalcareWebApplicetion?createDatabaseIfNotExist=true
spring.datasource.username=savindu
spring.datasource.password=gsavindu

#JPA configuration
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create

#jwt configurations
jwt.expiration=864000000
jwt.secretKey=mysecrty3424WEe32fmysecrty3424WEe32fmysecrty3424WEe32fmysecrty3424WEe32f

#capital leter simple leter ilakkam dala me key eka hadanna
# hama reqest ekakma blok karanne na   token ekak nathi  userkenek register wenakota ena reqest eka   block wenna hoda na log unat passe thamai tocken ekak enne
# dan habai spring squrity  hinda hama endpoint ekakma blok wela ne thiyenne  eka nisa apita sidda wenawa login wena ekai  register wena ekai kiyana end poin 2ka  accsess karanna puluwan wenna one mthanadi
